# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.4
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: true
classname: Hexctionary
default_branch: main
description: An addon for Hex Casting, providing easier ways to auto-craft and perform
    nested crafting.
display_name: Hexctionary
github_repo: hexctionary
github_user: SuperKnux
homepage_url: https://superknux.github.io/hexctionary
java_package: deer.ski.hexctionary
kotlin_package: deer.ski.hexctionary
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 0.1.0
modid: hexctionary
sources_url: https://github.com/SuperKnux/hexctionary
