modid = "hexctionary"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexctionary/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/hexctionary/icon.png"
include = [
    "hexctionary",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexctionary"
author = "SuperKnux"
show_landing_text = false

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='(?P<is_per_world>make|makePerWorld)\("(?P<name>[^"]+)",\s*HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)"' }
_per_world_value = "makePerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/HexctionaryActions.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../Common/src"
java = "{src}/main/java/deer/ski/hexctionary"
kotlin = "{src}/main/kotlin/deer/ski/hexctionary"

[_fabric]
src = "../Fabric/src"
java = "{src}/main/java/deer/ski/hexctionary/fabric"
kotlin = "{src}/main/kotlin/deer/ski/hexctionary/fabric"

[_forge]
src = "../Forge/src"
java = "{src}/main/java/deer/ski/hexctionary/forge"
kotlin = "{src}/main/kotlin/deer/ski/hexctionary/forge"
